# Generated by Django 4.0.4 on 2022-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('duration', models.FloatField()),
                ('last_play', models.DateField(auto_now=True)),
            ],
        ),
    ]
